FROM ubuntu:latest

WORKDIR /app

COPY . /app

RUN pip install -r requirements.txt && \
    apt-get update && \
    apt-get install -y python3 python3-pip    
    pip3 install flask && \

EXPOSE 8080

CMD ["python3", "app.py", "run-server", "0.0.0.0:8000"]
