FROM ubuntu:latest

  #set the working directory
WORKDIR /app

  #copy the files to the working directory
COPY . /app

  #run the neccessary dependencies
RUN apt-get update && apt-get install -y python3 python3-pip

  
  # Run a command to start the application
CMD ["python3", "hello-world.py"]


