steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials cluster-1 --zone us-central1-c --project forward-map-432605-v5
    kubectl apply -f nginx/app.yaml


options:
  logging: CLOUD_LOGGING_ONLY
